### ISSUE TITLE
Problem in parsing sharedStrings

### ISSUE THREAD

**Issue by ghost** [stephen-hardy/xlsx.js#24]
// xlsx.js, line #54:
if (s = zip.file('xl/sharedStrings.xml')) { // Process sharedStrings
	s = s.asText().split(/&lt;t.*?&gt;/g); i = s.length;
	while(--i) { 
		sharedStrings[i - 1] = unescapeXML(s[i].substring(0, s[i].indexOf('&lt;/t&gt;'))); 
	} // Do not process i === 0, because s[0] is the text before first t element
}

an '&lt;si&gt;' element can have multiple '&lt;t&gt;' elements, so above code can cause (logical) parsing errors for particular files.

if (s = zip.file('xl/sharedStrings.xml')) { // Process sharedStrings
	s = s.asText().split(/&lt;si.*?&gt;/g); i = s.length;
	while(--i) { 
		sharedStrings[i - 1] = unescapeXML(s[i].replace(/&lt;\/?[^&gt;]+(&gt;|$)/g, '')); 
	} // Do not process i === 0, because s[0] is the text before first t element
}

in my case, i changed the code like above, then the issue had solved.

**Comment by grassick** [comment]
Incorporated in 2.3.2
